name: nklcb
description: "A project that allows you to see the tech blogs of each company at a glance."

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP 요청, HTML 렌더링, URL 열기
  http: ^1.2.1
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.3.0

  # 다국어 지원 및 로컬 데이터 저장
  intl: ^0.19.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: NanumSquare
      fonts:
        - asset: assets/fonts//NanumSquareL.ttf
          weight: 300
        - asset: assets/fonts//NanumSquareB.ttf
          weight: 400
        - asset: assets/fonts/NanumSquareB.ttf
          weight: 700
        - asset: assets/fonts/NanumSquareEB.ttf
          weight: 800
